// Code generated by scripts/gen-paths.py; DO NOT EDIT.

package api

func pathApp(projectID string, appID string) string {
	return encodePath("projects", projectID, "apps", appID)
}

func pathAppPublicAPIKeys(projectID string, appID string) string {
	return encodePath("projects", projectID, "apps", appID, "public_api_keys")
}

func pathAppStoreKitConfig(projectID string, appID string) string {
	return encodePath("projects", projectID, "apps", appID, "store_kit_config")
}

func pathApps(projectID string) string {
	return encodePath("projects", projectID, "apps")
}

func pathAuditLogs(projectID string) string {
	return encodePath("projects", projectID, "audit_logs")
}

func pathChart(projectID string, chartName string) string {
	return encodePath("projects", projectID, "charts", chartName)
}

func pathChartOptions(projectID string, chartName string) string {
	return encodePath("projects", projectID, "charts", chartName, "options")
}

func pathCustomer(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID)
}

func pathCustomerActionsAssignOffering(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "actions", "assign_offering")
}

func pathCustomerActionsGrantEntitlement(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "actions", "grant_entitlement")
}

func pathCustomerActionsRestorePurchaseByOrderID(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "actions", "restore_purchase_by_order_id")
}

func pathCustomerActionsRevokeGrantedEntitlement(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "actions", "revoke_granted_entitlement")
}

func pathCustomerActionsTransfer(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "actions", "transfer")
}

func pathCustomerActiveEntitlements(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "active_entitlements")
}

func pathCustomerAliases(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "aliases")
}

func pathCustomerAttributes(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "attributes")
}

func pathCustomerInvoices(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "invoices")
}

func pathCustomerPurchases(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "purchases")
}

func pathCustomerSubscriptions(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "subscriptions")
}

func pathCustomerVirtualCurrencies(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "virtual_currencies")
}

func pathCustomerVirtualCurrenciesTransactions(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "virtual_currencies", "transactions")
}

func pathCustomerVirtualCurrenciesUpdateBalance(projectID string, customerID string) string {
	return encodePath("projects", projectID, "customers", customerID, "virtual_currencies", "update_balance")
}

func pathCustomers(projectID string) string {
	return encodePath("projects", projectID, "customers")
}

func pathEntitlement(projectID string, entitlementID string) string {
	return encodePath("projects", projectID, "entitlements", entitlementID)
}

func pathEntitlementActionsArchive(projectID string, entitlementID string) string {
	return encodePath("projects", projectID, "entitlements", entitlementID, "actions", "archive")
}

func pathEntitlementActionsAttachProducts(projectID string, entitlementID string) string {
	return encodePath("projects", projectID, "entitlements", entitlementID, "actions", "attach_products")
}

func pathEntitlementActionsDetachProducts(projectID string, entitlementID string) string {
	return encodePath("projects", projectID, "entitlements", entitlementID, "actions", "detach_products")
}

func pathEntitlementActionsUnarchive(projectID string, entitlementID string) string {
	return encodePath("projects", projectID, "entitlements", entitlementID, "actions", "unarchive")
}

func pathEntitlementProducts(projectID string, entitlementID string) string {
	return encodePath("projects", projectID, "entitlements", entitlementID, "products")
}

func pathEntitlements(projectID string) string {
	return encodePath("projects", projectID, "entitlements")
}

func pathIntegrationsWebhook(projectID string, webhookIntegrationID string) string {
	return encodePath("projects", projectID, "integrations", "webhooks", webhookIntegrationID)
}

func pathIntegrationsWebhooks(projectID string) string {
	return encodePath("projects", projectID, "integrations", "webhooks")
}

func pathMetricsOverview(projectID string) string {
	return encodePath("projects", projectID, "metrics", "overview")
}

func pathOffering(projectID string, offeringID string) string {
	return encodePath("projects", projectID, "offerings", offeringID)
}

func pathOfferingActionsArchive(projectID string, offeringID string) string {
	return encodePath("projects", projectID, "offerings", offeringID, "actions", "archive")
}

func pathOfferingActionsUnarchive(projectID string, offeringID string) string {
	return encodePath("projects", projectID, "offerings", offeringID, "actions", "unarchive")
}

func pathOfferingPackages(projectID string, offeringID string) string {
	return encodePath("projects", projectID, "offerings", offeringID, "packages")
}

func pathOfferings(projectID string) string {
	return encodePath("projects", projectID, "offerings")
}

func pathPackage(projectID string, packageID string) string {
	return encodePath("projects", projectID, "packages", packageID)
}

func pathPackageActionsAttachProducts(projectID string, packageID string) string {
	return encodePath("projects", projectID, "packages", packageID, "actions", "attach_products")
}

func pathPackageActionsDetachProducts(projectID string, packageID string) string {
	return encodePath("projects", projectID, "packages", packageID, "actions", "detach_products")
}

func pathPackageProducts(projectID string, packageID string) string {
	return encodePath("projects", projectID, "packages", packageID, "products")
}

func pathPaywall(projectID string, paywallID string) string {
	return encodePath("projects", projectID, "paywalls", paywallID)
}

func pathPaywallActionsPublish(projectID string, paywallID string) string {
	return encodePath("projects", projectID, "paywalls", paywallID, "actions", "publish")
}

func pathPaywallActionsUnpublish(projectID string, paywallID string) string {
	return encodePath("projects", projectID, "paywalls", paywallID, "actions", "unpublish")
}

func pathPaywalls(projectID string) string {
	return encodePath("projects", projectID, "paywalls")
}

func pathProduct(projectID string, productID string) string {
	return encodePath("projects", projectID, "products", productID)
}

func pathProductActionsArchive(projectID string, productID string) string {
	return encodePath("projects", projectID, "products", productID, "actions", "archive")
}

func pathProductActionsUnarchive(projectID string, productID string) string {
	return encodePath("projects", projectID, "products", productID, "actions", "unarchive")
}

func pathProductCreateInStore(projectID string, productID string) string {
	return encodePath("projects", projectID, "products", productID, "create_in_store")
}

func pathProductPrice(projectID string, productID string, currency string) string {
	return encodePath("projects", projectID, "products", productID, "prices", currency)
}

func pathProductPrices(projectID string, productID string) string {
	return encodePath("projects", projectID, "products", productID, "prices")
}

func pathProductStoreState(projectID string, productID string) string {
	return encodePath("projects", projectID, "products", productID, "store_state")
}

func pathProductStoreStateOperation(projectID string, productID string, operationID string) string {
	return encodePath("projects", projectID, "products", productID, "store_state", operationID)
}

func pathProductTestStorePrices(projectID string, productID string) string {
	return encodePath("projects", projectID, "products", productID, "test_store_prices")
}

func pathProducts(projectID string) string {
	return encodePath("projects", projectID, "products")
}

func pathProjects() string {
	return encodePath("projects")
}

func pathPurchase(projectID string, purchaseID string) string {
	return encodePath("projects", projectID, "purchases", purchaseID)
}

func pathPurchaseActionsRefund(projectID string, purchaseID string) string {
	return encodePath("projects", projectID, "purchases", purchaseID, "actions", "refund")
}

func pathPurchaseEntitlements(projectID string, purchaseID string) string {
	return encodePath("projects", projectID, "purchases", purchaseID, "entitlements")
}

func pathStoreStatePlan(projectID string, planID string) string {
	return encodePath("projects", projectID, "store_state", "plans", planID)
}

func pathStoreStatePlans(projectID string) string {
	return encodePath("projects", projectID, "store_state", "plans")
}

func pathSubscription(projectID string, subscriptionID string) string {
	return encodePath("projects", projectID, "subscriptions", subscriptionID)
}

func pathSubscriptionActionsCancel(projectID string, subscriptionID string) string {
	return encodePath("projects", projectID, "subscriptions", subscriptionID, "actions", "cancel")
}

func pathSubscriptionActionsExtend(projectID string, subscriptionID string) string {
	return encodePath("projects", projectID, "subscriptions", subscriptionID, "actions", "extend")
}

func pathSubscriptionActionsRefund(projectID string, subscriptionID string) string {
	return encodePath("projects", projectID, "subscriptions", subscriptionID, "actions", "refund")
}

func pathSubscriptionAuthenticatedManagementURL(projectID string, subscriptionID string) string {
	return encodePath("projects", projectID, "subscriptions", subscriptionID, "authenticated_management_url")
}

func pathSubscriptionEntitlements(projectID string, subscriptionID string) string {
	return encodePath("projects", projectID, "subscriptions", subscriptionID, "entitlements")
}

func pathSubscriptionTransactions(projectID string, subscriptionID string) string {
	return encodePath("projects", projectID, "subscriptions", subscriptionID, "transactions")
}
