blank_issues_enabled: false
contact_links:
  - name: 🚥 RevenueCat system status
    url: https://status.revenuecat.com
    about: Check RevenueCat's API status
  - name: 🙋 Our online community
    url: https://community.revenuecat.com
    about: Please ask and answer questions at https://community.revenuecat.com
  - name: 🧾 Account or billing support
    url: https://app.revenuecat.com/settings/support
    about: Get help from our support team
  - name: ✨ Feature request
    url: https://app.revenuecat.com/settings/support
    about: Please use the Contact Us form instead of opening an issue. This is the best channel that allows us to keep track of feature requests.
