#!/usr/bin/env python3
"""Generate internal/api/paths_gen.go — one path builder per endpoint the CLI uses.

The path segments come from the spec, not hand-typed in each service method, so a
path rename upstream flows through here instead of drifting silently. The set of
builders is driven by docs/specs/cli-coverage.yaml (the endpoints the CLI
implements); each path is validated against the preprocessed spec so a coverage
entry that no longer exists upstream fails the build rather than generating a
dead route.

Usage: python3 scripts/gen-paths.py SPEC COVERAGE OUTPUT
  SPEC     preprocessed OpenAPI spec (public + beta overlay merged)
  COVERAGE docs/specs/cli-coverage.yaml
  OUTPUT   internal/api/paths_gen.go
"""

import re
import sys
import yaml

INITIALISMS = {"id": "ID", "url": "URL", "api": "API", "urls": "URLs"}

# Endpoints the CLI calls that the public spec doesn't document. They can't be
# spec-driven, so their service methods keep an inline encodePath and no builder
# is generated. Remove an entry once the endpoint lands in the spec (or overlay).
NON_SPEC_PATHS = {
    "/projects/{project_id}/invoices/{invoice_id}",  # rc invoices get — not in public v2 spec
}


def camel_words(segment, upper_first):
    """CamelCase a snake_case segment, honoring known initialisms."""
    out = []
    for i, word in enumerate(segment.split("_")):
        if word in INITIALISMS:
            out.append(INITIALISMS[word])
        elif i == 0 and not upper_first:
            out.append(word)
        else:
            out.append(word[:1].upper() + word[1:])
    return "".join(out)


def singularize(word):
    if word.endswith("ies"):
        return word[:-3] + "y"
    if word.endswith("s") and not word.endswith("ss"):
        return word[:-1]
    return word


def param_name(placeholder):
    """{app_user_id} -> appUserID"""
    return camel_words(placeholder.strip("{}"), upper_first=False)


def builder_for(path):
    """Return (func_name, [param_names], [encodePath args]) for a spec path."""
    segments = [s for s in path.split("/") if s]
    params, args, name_parts = [], [], []
    for i, seg in enumerate(segments):
        if seg.startswith("{"):
            p = param_name(seg)
            params.append(p)
            args.append(p)
            continue
        args.append(f'"{seg}"')
        name = camel_words(seg, upper_first=True)
        # A literal followed by a path param names a single item. Singularizing
        # keeps it distinct from the collection (offerings -> offering); when the
        # word doesn't pluralize (store_state), append the id's resource instead
        # so the item path can't collide with the collection.
        if i + 1 < len(segments) and segments[i + 1].startswith("{"):
            singular = singularize(name)
            if singular != name:
                name = singular
            else:
                base = re.sub(r"_(id|code|name)$", "", segments[i + 1].strip("{}"))
                name = name + camel_words(base, upper_first=True)
        name_parts.append(name)
    # Nearly every path lives under /projects/{project_id}; drop the redundant
    # leading "Project" when it isn't the whole name.
    if len(name_parts) > 1 and name_parts[0] == "Project":
        name_parts = name_parts[1:]
    return "path" + "".join(name_parts), params, args


def main():
    if len(sys.argv) != 4:
        print(f"Usage: {sys.argv[0]} SPEC COVERAGE OUTPUT", file=sys.stderr)
        sys.exit(1)
    spec_path, coverage_path, output_path = sys.argv[1:4]

    with open(spec_path) as f:
        spec_paths = set(yaml.safe_load(f).get("paths", {}))
    with open(coverage_path) as f:
        coverage = yaml.safe_load(f)

    used = sorted({e["path"] for e in coverage.get("endpoints", [])} - NON_SPEC_PATHS)

    builders, names, missing = {}, {}, []
    for path in used:
        if path not in spec_paths:
            missing.append(path)
            continue
        name, params, args = builder_for(path)
        if name in names and names[name] != path:
            print(
                f"error: paths {names[name]!r} and {path!r} both generate {name}()",
                file=sys.stderr,
            )
            sys.exit(1)
        names[name] = path
        builders[name] = (params, args)

    if missing:
        for path in missing:
            print(f"error: cli-coverage path not found in spec: {path}", file=sys.stderr)
        sys.exit(1)

    lines = [
        "// Code generated by scripts/gen-paths.py; DO NOT EDIT.",
        "",
        "package api",
        "",
    ]
    for name in sorted(builders):
        params, args = builders[name]
        sig = ", ".join(f"{p} string" for p in params)
        lines.append(f"func {name}({sig}) string {{")
        lines.append(f"\treturn encodePath({', '.join(args)})")
        lines.append("}")
        lines.append("")

    with open(output_path, "w") as f:
        f.write("\n".join(lines).rstrip() + "\n")

    print(f"Wrote {len(builders)} path builders to {output_path}")


if __name__ == "__main__":
    main()
